{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "acb1eb6d",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "from collections import deque\n",
    "\n",
    "ethiopia_graph = {\n",
    "    \"Addis Ababa\": [\"Adama\", \"Ambo\", \"Debre Birhan\"],\n",
    "    \"Adama\": [\"Addis Ababa\", \"Batu\", \"Assella\", \"Matahara\"],\n",
    "    \"Ambo\": [\"Addis Ababa\", \"Nekemte\"],\n",
    "    \"Debre Birhan\": [\"Addis Ababa\", \"Debre Sina\"],\n",
    "    \"Debre Sina\": [\"Debre Birhan\", \"Kemise\"],\n",
    "    \"Kemise\": [\"Debre Sina\", \"Dessie\"],\n",
    "    \"Dessie\": [\"Kemise\", \"Woldia\"],\n",
    "    \"Woldia\": [\"Dessie\", \"Lalibela\", \"Samara\"],\n",
    "    \"Lalibela\": [\"Woldia\"],\n",
    "    \"Samara\": [\"Woldia\", \"Gabi Rasu\"],\n",
    "    \"Gabi Rasu\": [\"Samara\"],\n",
    "    \"Nekemte\": [\"Ambo\", \"Gimbi\"],\n",
    "    \"Gimbi\": [\"Nekemte\", \"Dembi Dollo\"],\n",
    "    \"Dembi Dollo\": [\"Gimbi\"],\n",
    "    \"Batu\": [\"Adama\", \"Shashemene\"],\n",
    "    \"Assella\": [\"Adama\"],\n",
    "    \"Matahara\": [\"Adama\"],\n",
    "    \"Shashemene\": [\"Batu\", \"Hawassa\"],\n",
    "    \"Hawassa\": [\"Shashemene\", \"Dilla\"],\n",
    "    \"Dilla\": [\"Hawassa\", \"Bule Hora\"],\n",
    "    \"Bule Hora\": [\"Dilla\", \"Yabello\"],\n",
    "    \"Yabello\": [\"Bule Hora\", \"Moyale\"],\n",
    "    \"Moyale\": [\"Yabello\"]\n",
    "}\n",
    "\n",
    "\n",
    "class GraphSearch:\n",
    "    def __init__(self, graph):\n",
    "        self.graph = graph\n",
    "\n",
    "    def search(self, start, goal, strategy=\"bfs\"):\n",
    "        if strategy.lower() == \"bfs\":\n",
    "            return self.bfs(start, goal)\n",
    "        elif strategy.lower() == \"dfs\":\n",
    "            return self.dfs(start, goal)\n",
    "        else:\n",
    "            raise ValueError(\"Strategy must be 'bfs' or 'dfs'\")\n",
    "\n",
    " \n",
    "    def bfs(self, start, goal):\n",
    "        queue = deque()\n",
    "        queue.append((start, [start]))\n",
    "        visited = set()\n",
    "\n",
    "        while queue:\n",
    "            current, path = queue.popleft()\n",
    "\n",
    "            if current == goal:\n",
    "                return path\n",
    "\n",
    "            if current not in visited:\n",
    "                visited.add(current)\n",
    "\n",
    "                for neighbor in self.graph.get(current, []):\n",
    "                    if neighbor not in visited:\n",
    "                        queue.append((neighbor, path + [neighbor]))\n",
    "\n",
    "        return None\n",
    "\n",
    "\n",
    "    def dfs(self, start, goal):\n",
    "        stack = []\n",
    "        stack.append((start, [start]))\n",
    "        visited = set()\n",
    "\n",
    "        while stack:\n",
    "            current, path = stack.pop()\n",
    "\n",
    "            if current == goal:\n",
    "                return path\n",
    "\n",
    "            if current not in visited:\n",
    "                visited.add(current)\n",
    "\n",
    "                for neighbor in reversed(self.graph.get(current, [])):\n",
    "                    if neighbor not in visited:\n",
    "                        stack.append((neighbor, path + [neighbor]))\n",
    "\n",
    "        return None\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    searcher = GraphSearch(ethiopia_graph)\n",
    "\n",
    "    start_city = \"Addis Ababa\"\n",
    "    goal_city = \"Moyale\"\n",
    "\n",
    "    print(\"Start:\", start_city)\n",
    "    print(\"Goal:\", goal_city)\n",
    "\n",
    "    print(\"\\n BFS Search\")\n",
    "    bfs_path = searcher.search(start_city, goal_city, strategy=\"bfs\")\n",
    "    print(\"BFS Path:\", bfs_path)\n",
    "\n",
    "    print(\"\\n DFS Search\")\n",
    "    dfs_path = searcher.search(start_city, goal_city, strategy=\"dfs\")\n",
    "    print(\"DFS Path:\", dfs_path)\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
